#!/usr/bin/env node
// Generated by LiveScript 1.3.1
(function(){
  "use strict";
  var fs, docopt, shelljs, uid, cwd, _, doc, opts, chunks;
  fs = require('fs');
  docopt = require('docopt').docopt;
  shelljs = require('shelljs');
  uid = require('uid');
  cwd = process.cwd();
  _ = require('bluebird').promisifyAll(shelljs);
  doc = shelljs.cat(__dirname + "/docs/usage.md");
  opts = docopt(doc);
  process.stdin.setEncoding('utf8');
  chunks = "";
  process.stdin.on('readable', function(){
    var c;
    c = process.stdin.read();
    if (c != null) {
      return chunks = chunks + c;
    }
  });
  process.stdin.on('end', function(){
    var tempDir;
    tempDir = cwd + "/tmp-" + uid(8);
    console.log(opts);
    _.cp('-R', opts['--template'] + "/*", tempDir);
    console.log(chunks);
    chunks.to(tempDir + "/cookiecutter.json");
    return _.execAsync("cookiecutter --no-input " + tempDir).then(function(){
      return console.log("done.");
    });
  });
}).call(this);
